[package]
name = "clicknrip"
version = "1.8.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
migrate-sepolia = "sozo build && sozo migrate --profile sepolia"

[profile.sepolia]

[dependencies]
dojo = "1.8.0"
openzeppelin_access = "3.0.0"
openzeppelin_interfaces = "2.1.0"
openzeppelin_introspection = "3.0.0"
openzeppelin_presets = "3.0.0"
openzeppelin_security = "3.0.0"
starknet = "2.13.1"

[dev-dependencies]
dojo_snf_test = "1.8.0"
snforge_std = "0.51.0"

[[target.starknet-contract]]
build-external-contracts = [
  "dojo::world::world_contract::world",
  "openzeppelin_presets::ERC20Upgradeable"
]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]
