[sncast.dev-deployer]
account = "deployer"
accounts-file = "./accounts/dev/accounts.json"
url = "http://localhost:5050"

[sncast.dev-admin]
account = "admin"
accounts-file = "./accounts/dev/accounts.json"
url = "http://localhost:5050"

[sncast.dev-player]
account = "player"
accounts-file = "./accounts/dev/accounts.json"
url = "http://localhost:5050"
